Repository damilog/MATZIP, pull requests merged in 2022-02, with the labels that each got.

#9 [Chore/fe setup] 프론트 초기 세팅 진행
  frontend/.gitignore
  frontend/.prettierrc.js
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/common/Spinner/Spinner.tsx
  frontend/src/components/common/Spinner/index.ts
  frontend/src/index.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/RedirectToErrorPage.tsx
  frontend/src/router/index.ts
  frontend/src/router/paths.ts
  frontend/src/router/routes.ts
  frontend/src/styles/GlobalStyles.ts
  frontend/src/styles/theme.ts
  frontend/src/styles/themedComponents.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: 🧩chore

#14 [Chore/BE] H2 DB 연결을 위한 설정 및 JPA 기본 옵션 세팅 #13
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yaml
Labels: 🧩chore

#17 [Feat/fe#10] HomePage 마크업, 스타일링
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/assets/images/logo.png
  frontend/src/components/Filter/Filter.jsx
  frontend/src/components/Filter/index.js
  frontend/src/components/RestaurantCard/RestaurantCard.jsx
  frontend/src/components/RestaurantCard/index.js
  frontend/src/components/common/Footer/Footer.tsx
  frontend/src/components/common/Footer/index.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/Header/index.ts
  frontend/src/components/common/Spinner/Spinner.tsx
  frontend/src/components/common/Spinner/index.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/RedirectToErrorPage.tsx
  frontend/src/react-app-env.d.ts
  frontend/src/router/index.ts
  frontend/src/router/paths.ts
  frontend/src/router/routes.ts
  frontend/src/styles/GlobalStyles.ts
  frontend/src/styles/theme.ts
  frontend/src/styles/themedComponents.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: FE

#21 Feat/be#6
  backend/build.gradle
  backend/src/main/java/us/stcorp/team3/hackathonproject/HackathonProjectApplication.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/domain/Category.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/domain/Matzip.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/domain/MatzipReview.java
  backend/src/test/java/us/stcorp/team3/hackathonproject/HackathonProjectApplicationTests.java
Labels: ✨feat, BE

#23 [Feat] 공통 엔티티 추출 및 적용
  backend/src/main/java/us/stcorp/team3/hackathonproject/HackathonProjectApplication.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/common/BaseTimeEntity.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/domain/Category.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/domain/Matzip.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/domain/MatzipReview.java
  backend/src/main/resources/application.yaml
Labels: ✨feat, BE

#24 [Feat/fe#18] Place Page UI구현
  frontend/package.json
  frontend/src/components/PlaceCard/PlaceCard.jsx
  frontend/src/components/PlaceCard/index.js
  frontend/src/components/PlaceHeader/PlaceHeader.jsx
  frontend/src/components/PlaceHeader/index.js
  frontend/src/components/PlaceReview/PlaceReview.jsx
  frontend/src/components/PlaceReview/index.js
  frontend/src/components/PlaceReviewCard/PlaceReviewCard.jsx
  frontend/src/components/PlaceReviewCard/index.js
  frontend/src/components/RecommendedPlace/RecommendedPlace.jsx
  frontend/src/components/RecommendedPlace/index.js
  frontend/src/components/RestaurantCard/RestaurantCard.jsx
  frontend/src/components/RestaurantCard/index.js
  frontend/src/components/ReviewInput/ReviewInput.jsx
  frontend/src/components/ReviewInput/index.js
  frontend/src/components/common/PlaceCarousel/PlaceCarousel.jsx
  frontend/src/components/common/PlaceCarousel/index.js
  frontend/src/components/common/SelectModal/SelectModal.jsx
  frontend/src/components/common/SelectModal/index.js
  frontend/src/components/common/Spinner/Spinner.tsx
  frontend/src/components/common/StarRating/StarRating.jsx
  frontend/src/components/common/StarRating/index.js
  frontend/src/hooks/useToggle.js
  frontend/src/pages/Home.tsx
  frontend/src/pages/Place.jsx
  frontend/src/router/paths.ts
  frontend/src/router/routes.ts
  frontend/src/styles/theme.ts
  frontend/yarn.lock
Labels: ✨feat, FE

#30 [Feat/fe#19] Edit Page 마크업
  frontend/src/components/EditorForm/EditorForm.jsx
  frontend/src/components/EditorForm/index.js
  frontend/src/components/Filter/Filter.jsx
  frontend/src/components/PlaceHeader/PlaceHeader.jsx
  frontend/src/components/RecommendedPlace/RecommendedPlace.jsx
  frontend/src/components/ReviewInput/ReviewInput.jsx
  frontend/src/components/common/BackButton/BackButton.jsx
  frontend/src/components/common/BackButton/index.js
  frontend/src/components/common/GradientButton/GradientButton.jsx
  frontend/src/components/common/GradientButton/index.js
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/SelectBox/SelectBox.jsx
  frontend/src/components/common/SelectBox/index.js
  frontend/src/components/common/StarRating/StarRating.jsx
  frontend/src/components/common/TextInput/TextInput.jsx
  frontend/src/components/common/TextInput/index.js
  frontend/src/pages/Editor.jsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Place.jsx
  frontend/src/pages/RedirectToErrorPage.tsx
  frontend/src/router/paths.ts
  frontend/src/router/routes.ts
  frontend/src/styles/theme.ts
Labels: ✨feat, FE

#31 [PR] ML Server (#4 / #5)
  .gitignore
  ml-server/README.md
  ml-server/__init__.py
  ml-server/main.py
  ml-server/utils/DBHelper.py
  ml-server/utils/MLHelper.py
  ml-server/utils/__init__.py
  ml-server/utils/data.pickle
  ml-server/utils/kmode_model.pkl
Labels: ✨feat, ML

#29 [Feat] 전체 조회 API 구현
  backend/src/main/java/us/stcorp/team3/hackathonproject/HackathonProjectApplication.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/common/config/JpaAuditionConfig.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/controller/MatzipController.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/dto/EntireMatzipResponse.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/repository/MatzipRepository.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipService.java
  backend/src/test/java/us/stcorp/team3/hackathonproject/controller/MatzipControllerTest.java
Labels: ✨feat, BE

#38 [PR] DB 스키마 변경에 따른 SQL Query 변경 (#34)
  ml-server/utils/DBHelper.py
Labels: 🛠fix, ML

#37 [Hotfix]: Category 도메인 삭제 및 Enum 변경
  backend/src/main/java/us/stcorp/team3/hackathonproject/domain/Category.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/domain/Matzip.java
  backend/src/test/java/us/stcorp/team3/hackathonproject/controller/MatzipControllerTest.java
Labels: 🛠fix, BE

#40 [PR] ML README
  README.md
Labels: 📝docs, ML

#41 [Feat] 새로운 맛집 등록 API
  backend/src/main/java/us/stcorp/team3/hackathonproject/HackathonProjectApplication.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/controller/MatzipController.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/domain/Matzip.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/dto/EntireMatzipResponse.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/dto/MatzipRequest.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipService.java
  backend/src/test/java/us/stcorp/team3/hackathonproject/controller/MatzipControllerTest.java
Labels: ✨feat, BE

#50 [PR] Refactor Entity Field Type
  backend/src/main/java/us/stcorp/team3/hackathonproject/domain/Matzip.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/dto/EntireMatzipResponse.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/dto/MatzipRequest.java
  backend/src/test/java/us/stcorp/team3/hackathonproject/controller/MatzipControllerTest.java
Labels: ⚙️refactor, BE

#56 [PR] ML OpenAPI 구축
  ml-server/README.md
  ml-server/main.py
Labels: ✨feat, ML

#58 [PR] BE OpenAPI 구축
  backend/build.gradle
  backend/src/main/resources/application.yaml
Labels: ✨feat, BE

#60 [Feat/fe#11,#55] Home UI(pagination, myMenu) 구현
  frontend/package.json
  frontend/src/components/EditorForm/EditorForm.jsx
  frontend/src/components/MyMenu/MyMenu.jsx
  frontend/src/components/MyMenu/index.js
  frontend/src/components/PlaceCard/PlaceCard.jsx
  frontend/src/components/PlaceReviewCard/PlaceReviewCard.jsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/SelectModal/SelectModal.jsx
  frontend/src/components/common/Spinner/Spinner.tsx
  frontend/src/pages/Home.tsx
  frontend/src/router/paths.ts
  frontend/src/router/routes.ts
  frontend/src/store/homeStore.js
  frontend/src/util/API/index.js
  frontend/src/util/API/instance.js
  frontend/src/util/API/interceptor.js
  frontend/yarn.lock
Labels: ✨feat, FE

#61 [Feat] 맛집 리뷰 등록
  backend/src/main/java/us/stcorp/team3/hackathonproject/controller/MatzipController.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/domain/MatzipReview.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/dto/MatzipReviewRequest.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipReviewService.java
  backend/src/test/java/us/stcorp/team3/hackathonproject/controller/MatzipControllerTest.java
Labels: ✨feat, BE

#62 [Feat] 카테고리별 필터 기능
  backend/src/main/java/us/stcorp/team3/hackathonproject/controller/MatzipController.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/dto/MatzipResponse.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/dto/MatzipReviewResponse.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/dto/ReviewResponse.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/repository/MatzipRepository.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipService.java
  backend/src/test/java/us/stcorp/team3/hackathonproject/controller/MatzipControllerTest.java
Labels: ✨feat, BE

#65 [PR] ML SQL 변경
  ml-server/utils/DBHelper.py
Labels: 🛠fix, ML

#66 [Feat] 맛집 리뷰 삭제 기능 구현
  backend/src/main/java/us/stcorp/team3/hackathonproject/controller/MatzipController.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipReviewService.java
Labels: ✨feat, BE

#69 [Feat] 맛집 수정 기능
  backend/src/main/java/us/stcorp/team3/hackathonproject/controller/MatzipController.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/domain/Matzip.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipService.java
Labels: ✨feat, BE

#71 [Feat] 조회수 증가 기능
  backend/src/main/java/us/stcorp/team3/hackathonproject/domain/Matzip.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipService.java
Labels: ✨feat, BE

#74 refactor: 맛집 리뷰 등록시 맛집 평점에 반영 (#67)
  backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipReviewService.java
Labels: ⚙️refactor, BE

#75 [Refactor] 응답 스펙 변경
  backend/src/main/java/us/stcorp/team3/hackathonproject/common/config/QuerydslConfig.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/controller/MatzipController.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/dto/MatzipResponse.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/repository/MatzipRepository.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/repository/MatzipRepositoryCustom.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/repository/MatzipRepositoryImpl.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipReviewService.java
  backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipService.java
  backend/src/test/java/us/stcorp/team3/hackathonproject/controller/MatzipControllerTest.java
Labels: ✨feat, BE

#78 ✨ refactor: 평점별 Sorting - #77
  backend/src/main/java/us/stcorp/team3/hackathonproject/repository/MatzipRepositoryImpl.java
Labels: 🛠fix, BE

#82 [Feat/fe#81] Pagination 적용
  frontend/src/components/Filter/Filter.jsx
  frontend/src/pages/Home.jsx
  frontend/src/store/homeStore.js
Labels: ✨feat, FE

#84 feat: 추천 맛집으로 이동 구현 (#83)
  frontend/src/components/PlaceCard/PlaceCard.jsx
Labels: ✨feat, FE

#86 ✨ fix: 평점 평균 계산 로직 변경 - #85
  backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipReviewService.java
Labels: 🛠fix, BE

#87 [Feat/fe#80] 맛집 추가, 삭제 기능 구현
  frontend/src/components/EditorForm/EditorForm.jsx
  frontend/src/components/PlaceReviewCard/PlaceReviewCard.jsx
  frontend/src/components/ReviewInput/ReviewInput.jsx
  frontend/src/components/common/PlaceCarousel/PlaceCarousel.jsx
  frontend/src/components/common/SelectBox/SelectBox.jsx
  frontend/src/components/common/SelectModal/SelectModal.jsx
  frontend/src/pages/Home.jsx
  frontend/src/service/EditorService.js
Labels: ✨feat, FE

#88 fix: postReview 안되는 문제 해결
  frontend/src/components/ReviewInput/ReviewInput.jsx
Labels: 🛠fix, FE

#95 [Feat/fe#52] 불필요한 코드 삭제
  frontend/src/components/PlaceReview/PlaceReview.jsx
  frontend/src/pages/Place.jsx
  frontend/src/service/EditorService.js
  frontend/src/store/editorStore.js
  frontend/src/store/homeStore.js
  frontend/src/store/placeStore.js
Labels: 🛠fix, FE
